### ISSUE TITLE
Bad installation?

### ISSUE THREAD

**Issue by djalmaaraujo** [fnando/coupons#2]
I added to the config/routes.rb and when I try to start the application, I get this error:

```
Exiting
/Users/cooper/dev/flatzon/config/routes.rb:61:in `block in <top (required)>': uninitialized constant Coupons::Engine (NameError)
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:423:in `instance_exec'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:423:in `eval_block'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:401:in `draw'
    from /Users/cooper/dev/flatzon/config/routes.rb:1:in `<top (required)>'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:40:in `each'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:40:in `load_paths'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:16:in `reload!'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:26:in `block in updater'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.0/lib/active_support/file_update_checker.rb:75:in `call'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.0/lib/active_support/file_update_checker.rb:75:in `execute'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:27:in `updater'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /Users/cooper/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
    from /Users/cooper/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
    from /Users/cooper/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
    from /Users/cooper/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
    from /Users/cooper/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each'
    from /Users/cooper/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `call'
    from /Users/cooper/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
    from /Users/cooper/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
    from /Users/cooper/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
    from /Users/cooper/dev/flatzon/config/environment.rb:5:in `<top (required)>'
    from /Users/cooper/dev/flatzon/config.ru:3:in `block in <main>'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/rack-1.6.0/lib/rack/builder.rb:55:in `instance_eval'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/rack-1.6.0/lib/rack/builder.rb:55:in `initialize'
    from /Users/cooper/dev/flatzon/config.ru:in `new'
    from /Users/cooper/dev/flatzon/config.ru:in `<main>'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/rack-1.6.0/lib/rack/builder.rb:49:in `eval'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/rack-1.6.0/lib/rack/builder.rb:49:in `new_from_string'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/rack-1.6.0/lib/rack/builder.rb:40:in `parse_file'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/rack-1.6.0/lib/rack/server.rb:299:in `build_app_and_options_from_config'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/rack-1.6.0/lib/rack/server.rb:208:in `app'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/commands/server.rb:61:in `app'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/rack-1.6.0/lib/rack/server.rb:336:in `wrapped_app'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/commands/server.rb:139:in `log_to_stdout'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/commands/server.rb:78:in `start'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:80:in `block in server'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `tap'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `server'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
    from /Users/cooper/dev/flatzon/bin/rails:8:in `require'
    from /Users/cooper/dev/flatzon/bin/rails:8:in `<top (required)>'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@flatzon/gems/spring-1.3.3/lib/spring/client/rails.rb:27:in `load'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@flatzon/gems/spring-1.3.3/lib/spring/client/rails.rb:27:in `call'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@flatzon/gems/spring-1.3.3/lib/spring/client/command.rb:7:in `call'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@flatzon/gems/spring-1.3.3/lib/spring/client.rb:26:in `run'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@flatzon/gems/spring-1.3.3/bin/spring:48:in `<top (required)>'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@flatzon/gems/spring-1.3.3/lib/spring/binstub.rb:11:in `load'
    from /Users/cooper/.rvm/gems/ruby-2.2.0@flatzon/gems/spring-1.3.3/lib/spring/binstub.rb:11:in `<top (required)>'
    from /Users/cooper/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/cooper/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/cooper/dev/flatzon/bin/spring:13:in `<top (required)>'
    from bin/rails:3:in `load'
    from bin/rails:3:in `<main>'
```

**Comment by djalmaaraujo** [comment]
Maybe it's just lack of documentation on how to include the class?

**Comment by fabianoleittes** [comment]
I went to do a test and had same problem.

**Comment by frankyston** [comment]
I also had the same problem, but I'm checking how to fix

**Comment by fnando** [comment]
Sorry for not responding sooner. The lib isn't published yet, so you're all installing an empty stub. Just point to master repo like `gem 'coupons', github: 'fnando/coupons'` for now.

**Comment by vibhoo** [comment]
Gem is not compatible with rails 3.2.17

**Comment by megetron** [comment]
Happens to me too. @fnando post solved it to me. thanks.

**Comment by SaiVardhan** [comment]
Thanks @fnando your solution solved the issue

**Comment by pankhuri** [comment]
Will it not work with rails 4.1.5 ?
